version: "3.9"

services:
  frontend:
    build: .
    command: npm start
    expose:
      - "3000"
    volumes:
      - ./public:/app/public
      - ./src:/app/src
    environment:
      - FAST_REFRESH=false
      - CHOKIDAR_USEPOLLING=true

networks:
  default:
    name: tandem-network
    external: true