version: "3.9"

services:
  frontend:
    build: .
    command: sh -c "npm run build && serve -s /app/build"
    expose:
      - "3000"

networks:
  default:
    name: tandem-network
    external: true